language: java

jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
  
env:
- TERM=dumb

before_script:
  - ./gradlew setupCIWorkspace

script: ./gradlew buildNeeded

after_success:
- ./gradlew cobertura
- ./gradlew coveralls
